package com.example.taskmaster

object Versions {
    const val gradlePlugin = "7.3.0"
    const val kotlin = "1.8.20"
    const val compose = "1.4.0"
    const val composeCompiler = "1.4.2"
    const val coroutines = "1.7.0"
    const val serialization = "1.4.1"
    const val mviKotlin = "3.1.0"
    const val decompose = "1.0.0-compose-experimental"
    const val essenty = "1.0.0"
    const val ktor = "2.2.3"
    const val sqlDelight = "2.0.0-alpha05"
    const val koin = "3.2.0"
    const val imageLoader = "1.2.10"
    const val logbackClassic = "1.2.11"
    const val kotlinWrappersBom = "1.0.0-pre.510"
    const val multiplatformSettings = "0.8.1"
    const val napier = "2.4.0"
    const val lifecycle = "2.4.0"
    const val accompanist = "0.20.0"
    const val navigation = "2.4.0-alpha02"
    const val coil = "1.4.0"
    const val firebaseBOM = "29.0.3"
    const val splashScreen = "1.0.0-beta01"
    const val lottie = "5.0.3"
    const val desugaring = "1.1.5"
    const val composeActivity = "1.4.0"
    const val composeConstraint = "1.0.0-rc01"
    const val androidCore = "1.7.0"
    const val appCompat = "1.4.1"
    const val material = "1.4.0"
}